package edu.ncsu.csc411.ps03.agent;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import edu.ncsu.csc411.ps03.environment.Environment;

/**
	Represents a linear assignment problem where N workers must be assigned
	to N tasks. Each worker/task combination is further associated with some
	value. The goal of this task is the produce an optimal configuration that
	maximizes (or minimizes) the sum of the assigned worker/task values.
*/

public class ConfigurationSolver {
	private Environment env;
	private int[] configuration;
	private int[] bestConfiguration;
	private double temp;
	private double decay;
	private int[][] parents;
	private boolean firstGen;
	private double mutation;
	
	/** Initializes a Configuration Solver for a specific environment. */
	public ConfigurationSolver (Environment env) { 
		this.env = env;
		this.configuration = new int[this.env.getNumWorkers()];
		// Initializing by assigning work to an arbitrary task
		for(int i = 0; i < this.configuration.length; i++) {
			this.configuration[i] = i;
		}
		// Need to clone because of how Java handles assigning arrays
		// as values (relative referencing). Recall this is similar to
		// that one lecture in CSC 116 where if we don't duplicate the second
		// array, it will constantly change as this.configuration changes.
		// Cloning the array resolves this issue.
		this.bestConfiguration = this.configuration.clone();
		
		//Current temp over the iterations, starts at 100 cause probability is out of 100
		this.temp = 100;
		this.decay = 0.9;
		this.firstGen = true;
		this.parents = new int[2][];
		this.mutation = 0.258;
	}
	
	/**
    	Problem Set 03 - For this Problem Set, you will be exploring search
    	methods for optimal configurations. In this exercise, you are given
    	a linear assignment problem, where you must determine the appropriate
    	configuration assignments for persons to tasks. Specifically, you are
    	seeking to MAXIMIZE the fitness score of this configuration. While brute
    	forcing your search will provide you with the optimal solution, you run
    	into the issue that there are N! possible permutations, which can increase
    	your search space as N increases. Instead, utilize one of the search methods
    	presented in class to tackle this problem.
    	
    	For the updateSearch(), design an algorithm that will iterate through an
    	iterative optimization algorithm, updating the current configuration as it
    	traverses its search space. The updateSearch() method should also return this
    	configuration back to the environment. For example, in an N=5 problem space, 
    	updateSearch() may return {4,1,2,3,0}, where Worker #4 is assigned Task #3.
    	
    	NOTE - simply doing random search, while it "will" work, is not permitted. If we
    	see you implementation is just random search, you will receive a -40% penalty to
    	your submission. Instead, think about the meta-heuristics presented in class, which
    	use "controlled" randomization.
	 */

	/**
			My implementation is based on the simulated annealing approach talked about in the lecture. First,
		a list of neighbors is created, obtained by taking the current config and swapping every element.
			After this, it will go through that list and find the new best config if it exists. I decided
		on this, even though it was not in the lecture, as it would not take that much time since the algorithm
		already relied on two nested for loops, so one more is not that bad.
			Next, it will pick a random neighbor from the list to potentially go to. If it is a better config, it will
		always go, but if it isn't, then a probability check is taken. Probability is calculated by using e
		to the power of (the change between the current config score and random neighbor config score divided by
		the temp). This is then checked against a random number, and if it passes, the config is updated.
			Finally, the temp is updated and the config is returned.
			
			
			I have also created a genetic algorithm. The idea behind that was take the top performer and
		a random config to create the new generation.
			The first generation is made by shuffling whatever given configs there are. It also checks to see
		if any of the ones made are the new best configuration. After this though, no more random configs.
			The genetic part of the algorithm comes in later, with children being generated by a crossover point.
		The children are made from the best configuration found, along with some random other parent that is not
		the best config. Crossover point then picks where the best config stops and the random config begins in the
		creation of a new child. This is done 50 times, although this number is arbitrary, and the approach
		would likely work better if I allow more children to be made. After a child is made, a mutation is allowed
		to occur, which ends up just swapping two random indices, that are potentially the same index. These children
		are added to a list, and then control flows back to the genetic algorithm.
			We then check the children to see if they are a new best, and update it accordingly. We then make the
		best config parent[0] and a random child parent[1], with them being different arrays. It then returns the best
		config as the current.
	 */
	public int[] updateSearch () {
		
		/**
		// Random Search (aka -40% penalty if you use this)
		ArrayList<Integer> intList = new ArrayList<Integer>();
		for(int val : this.configuration)
			intList.add(val);
		Collections.shuffle(intList);
		for(int i = 0; i < this.configuration.length; i++)
			this.configuration[i] = intList.get(i);
		System.out.println(Arrays.toString(this.configuration) + " = " + env.calcScore(this.configuration));
		if (env.calcScore(this.configuration) > env.calcScore(bestConfiguration))
			this.bestConfiguration = this.configuration.clone();
		return this.configuration;
		*/
		
		//My work starts here
		
		
		//If you want to see the genetic approach I created, uncomment this
		//return geneticApproach();
		
		//Get all the neighbors
		
		ArrayList<int[]> neighbors = getNeighbors(this.configuration);
		
		//Pick a random neighbor to maybe go to
		int randIndex = (int) (Math.random() * (neighbors.size() - 1));
		int[] randomNeighbor = neighbors.get(randIndex);
		int comparison = env.calcScore(randomNeighbor) - env.calcScore(this.configuration);
		//If it is better, just set it as the new config
		if(env.calcScore(randomNeighbor) > env.calcScore(bestConfiguration)) {
			bestConfiguration = randomNeighbor;
		}
		if(comparison > 0) {
			this.configuration = randomNeighbor;
		}
		else {
			//If it passes the probability check, go to it anyways, even though its bad
			double prob = Math.pow(Math.E, (comparison / getTemp()));
			if(Math.random() < prob) {
				this.configuration = randomNeighbor;
			}
		}
		
		
		//Apply decay to the temp to make it less malleable
		updateTemp();
		return this.configuration;
		
	}
	
	/**
	 * In addition to updateSearch, you should also track you BEST OBSERVED CONFIGURATION.
	 * While your search may move to worse configurations (since that's what the algorithm
	 * needs to do), getBestConfiguration will return the best observed configuration by your
	 * agent.
	 * You do not need to change this method. Update bestConfiguration in updateSearch.
	*/
	public int[] getBestConfiguration() {
		return this.bestConfiguration;
	}
	
	private void updateTemp() {
		this.temp = (int) (this.temp * decay);
	}
	
	private double getTemp() {
		return temp;
	}
	
	private ArrayList<int[]> getNeighbors(int[] config) {
		ArrayList<int[]> neighbors = new ArrayList<int[]>();
		for(int i = 0; i < config.length; i++) {
			for(int j = 0; j < config.length; j++) {
				if(i != j) {
					int[] newConfig = Arrays.copyOf(config, config.length);
					int temp = newConfig[j];
					newConfig[j] = newConfig[i];
					newConfig[i] = temp;
					neighbors.add(newConfig);
				}
			}
		}
		return neighbors;
	}
	
	
	//Code below here is used in my genetic algorithm
	private int[] geneticApproach() {
		if(firstGen) {
			parents[0] = this.configuration;
			//Need some other random config to be the other first parent
			ArrayList<Integer> intList = new ArrayList<Integer>();
			for(int val : this.configuration)
				intList.add(val);
			Collections.shuffle(intList);
			for(int i = 0; i < this.configuration.length; i++)
				this.configuration[i] = intList.get(i);
			parents[1] = this.configuration;
			//Set them to best or second best if they meet requirements
			//If its the best, make it best
			if(env.calcScore(parents[0]) > env.calcScore(bestConfiguration)) {
				bestConfiguration = parents[0];
			}
			//If its the best, make it the best
			if(env.calcScore(parents[1]) > env.calcScore(bestConfiguration)) {
				bestConfiguration = parents[1];
			}
			
			firstGen = false;
			if(parents[0] == null) {
				System.out.println("Parent 0 is null.");
			}
			if(parents[1] == null) {
				System.out.println("Parent 1 is null.");
			}
		}
		//Parents are set up regardless now, go
		ArrayList<int[]> children = getChildren();
		for(int i = 0; i < children.size(); i++) {
			if(env.calcScore(children.get(i)) > env.calcScore(bestConfiguration)) {
				bestConfiguration = children.get(i);
			}
		}
		this.configuration = this.bestConfiguration;
		parents[0] = this.configuration;
		int[] randomOtherParent;
		int randInd = (int) (Math.random() * (children.size() - 1));
		randomOtherParent = children.get(randInd);
		while(randomOtherParent == parents[0]) {
			randInd = (int) (Math.random() * (children.size() - 1));
			randomOtherParent = children.get(randInd);
		}
		parents[1] = randomOtherParent;
		
		return this.configuration;
		
		
	}
	
	private ArrayList<int[]> getChildren() {
		ArrayList<int[]> children = new ArrayList<int[]>();
		//50 kids
		for(int i = 0; i < 50; i++) {
			int divider = (int) (Math.random() * (parents[0].length - 1));
			int[] newChild = new int[parents[0].length];
			for(int j = 0; j < parents[0].length; j++) {
				if(j < divider) {
					newChild[j] = parents[0][j];
				}
				else {
					newChild[j] = parents[1][j];
				}
				
			}
			//Mutation code
			//Note that a mutation can end up doing nothing
			if(Math.random() < mutation) {
				int firstInd = (int) (Math.random() * (newChild.length - 1));
				int secondInd = (int) (Math.random() * (newChild.length - 1));
				int temp = newChild[firstInd];
				newChild[firstInd] = newChild[secondInd];
				newChild[secondInd] = temp;
			}
			children.add(newChild);
		}
		return children;
		
		
	}
 	
}